### PR TITLE
Remove manual step

### PR DESCRIPTION
**Pull request by phasebash**

### CODE REVIEW

**Review by ztbrown — CHANGES_REQUESTED** [review]
We don't need to do a checkout step anymore, we can get rid of all of the `agent {}` blocks in each stage and the pipeline agent should be `any`.

**Comment by ztbrown** [comment]
And I don't think we need the clean workspace step either.

**Comment by phasebash** [comment]
what's left to move this forward?

**Comment by ztbrown** [comment]
@phasebash I removed the checkout stage because I felt like it runs counter to the idea of a declarative pipeline. This necessitated removal of the workspace clean step. If we need that step for something, let me know, but it doesn't seem like we do.

**Review by ztbrown — APPROVED** [review]

**Pull request merged**
